/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package cl.duoc.viwes;

/**
 *
 * @author Maxte
 */
public class Menu extends javax.swing.JFrame {

    /**
     * Creates new form Menu
     */
    public Menu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitulo = new javax.swing.JLabel();
        lblSubTitulo = new javax.swing.JLabel();
        lblOtroMenu = new javax.swing.JLabel();
        btnOtroMenu = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        mnuAgregar = new javax.swing.JMenuItem();
        mnuListar = new javax.swing.JMenuItem();
        mnuModificarAlumno = new javax.swing.JMenuItem();
        munElminar = new javax.swing.JMenuItem();
        mnuSalir = new javax.swing.JMenu();
        mnuExit = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblTitulo.setFont(new java.awt.Font("Serif", 1, 36)); // NOI18N
        lblTitulo.setText("Bienvenido Al Repaso");

        lblSubTitulo.setFont(new java.awt.Font("Serif", 1, 18)); // NOI18N
        lblSubTitulo.setText("Esta ventana es para Visualizar alumnos donde solo se puede ver el nombre y su edad");

        lblOtroMenu.setFont(new java.awt.Font("Serif", 1, 14)); // NOI18N
        lblOtroMenu.setText("Te gustaria ver el otro menu?");

        btnOtroMenu.setText("Otro Menu");
        btnOtroMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOtroMenuActionPerformed(evt);
            }
        });

        jMenu1.setText("Inicio");

        mnuAgregar.setText("Agregar");
        mnuAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuAgregarActionPerformed(evt);
            }
        });
        jMenu1.add(mnuAgregar);

        mnuListar.setText("Listar");
        mnuListar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuListarActionPerformed(evt);
            }
        });
        jMenu1.add(mnuListar);

        mnuModificarAlumno.setText("Modificar");
        mnuModificarAlumno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuModificarAlumnoActionPerformed(evt);
            }
        });
        jMenu1.add(mnuModificarAlumno);

        munElminar.setText("Eliminar");
        munElminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                munElminarActionPerformed(evt);
            }
        });
        jMenu1.add(munElminar);

        jMenuBar1.add(jMenu1);

        mnuSalir.setText("Salir");

        mnuExit.setText("Salir");
        mnuExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuExitActionPerformed(evt);
            }
        });
        mnuSalir.add(mnuExit);

        jMenuBar1.add(mnuSalir);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(96, 96, 96)
                        .addComponent(lblTitulo))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblSubTitulo)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(lblOtroMenu)
                        .addGap(20, 20, 20))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnOtroMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(34, 34, 34))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addComponent(lblTitulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblSubTitulo)
                .addGap(93, 93, 93)
                .addComponent(lblOtroMenu)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnOtroMenu)
                .addContainerGap(160, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mnuAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuAgregarActionPerformed
        AgregarAlumno alumno = new AgregarAlumno();
        alumno.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_mnuAgregarActionPerformed

    private void mnuExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuExitActionPerformed
        System.exit(0);
    }//GEN-LAST:event_mnuExitActionPerformed

    private void mnuListarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuListarActionPerformed
        ListarAlumno listalmuno = new ListarAlumno();
        listalmuno.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_mnuListarActionPerformed

    private void mnuModificarAlumnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuModificarAlumnoActionPerformed
        ModificarAlumno modAlumno = new ModificarAlumno();
        modAlumno.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_mnuModificarAlumnoActionPerformed

    private void munElminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_munElminarActionPerformed
        EliminarAlumno eliAlumno = new EliminarAlumno();
        eliAlumno.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_munElminarActionPerformed

    private void btnOtroMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOtroMenuActionPerformed
        Menu2 menu = new Menu2();
        menu.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnOtroMenuActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnOtroMenu;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JLabel lblOtroMenu;
    private javax.swing.JLabel lblSubTitulo;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JMenuItem mnuAgregar;
    private javax.swing.JMenuItem mnuExit;
    private javax.swing.JMenuItem mnuListar;
    private javax.swing.JMenuItem mnuModificarAlumno;
    private javax.swing.JMenu mnuSalir;
    private javax.swing.JMenuItem munElminar;
    // End of variables declaration//GEN-END:variables
}
